version: "3.4"
services:
  app:
    build:
      context: ../../
      dockerfile: ./resources/docker/Dockerfile
    working_dir: /web/html/
    volumes:
      - ../../src/:/web/html/
      - ../../resources/certs:/etc/nginx/certs
    env_file: ../../src/.env
    environment:
      - LOG_FILES=false
      - DB_MIGRATE=true
      - DB_PORT=3306
      - DB_HOST=database
      - DB_DATABASE=lan_manager
      - DB_USERNAME=lan_manager
      - DB_PASSWORD=password
    container_name: lan_manager_app
    ports:
      - 80:80
      - 443:443
  database:
    image: mysql:5.6
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=lan_manager
      - MYSQL_USER=lan_manager
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - "3306:3306"
    container_name: lan_manager_database
volumes:
  db:
    name: lan_manager_db
