name: Test and Build

on:
  push:
    branches: 
      - master
      - dev
      - 'renovate/**'
      - 'feature/**'
  pull_request:
    branches: 
      - master
      - dev
      - 'renovate/**'
      - 'feature/**'
  repository_dispatch: # Allows action to be triggered via webhook
  workflow_dispatch: # Allows action to be run manually from the Actions tab

jobs:
  build-docker:
      runs-on: 'ubuntu-latest'
      steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.0.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: prepare permissions
        run: chown -R 82:82 src
      - name: get dependencies
        run: make app-build-dep
      - name: Login to DockerHub
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Linux Image
        if: ${{ github.event_name == 'pull_request' }}
        uses: docker/build-push-action@v3.1.1
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v7
          tags: |
            lan2play/eventula-manager:latest
          build-args: |
            BUILDNODE=GitHub (Run Number: ${{ github.run_number }} Run ID: ${{ github.run_id }})
            BUILDID=${{ github.run_id }}
            BUILDNUMBER=${{ github.run_number }}
            SOURCE_COMMIT=${{ github.sha }}
          no-cache: true
          push: false      
      - name: Build and push Linux Image
        if: ${{ startsWith(github.ref, 'refs/tags/master') && github.event_name == 'push' }}
        uses: docker/build-push-action@v3.1.1
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v7
          tags: |
            lan2play/eventula-manager:latest
          build-args: |
            BUILDNODE=GitHub (Run Number: ${{ github.run_number }} Run ID: ${{ github.run_id }})
            BUILDID=${{ github.run_id }}
            BUILDNUMBER=${{ github.run_number }}
            SOURCE_COMMIT=${{ github.sha }}
          no-cache: true
          push: true
      - name: Build and push Linux Image dev
        if: ${{ startsWith(github.ref, 'refs/tags/dev') && github.event_name == 'push' }}
        uses: docker/build-push-action@v3.1.1
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v7
          tags: |
            lan2play/eventula-manager:dev
          build-args: |
            BUILDNODE=GitHub (Run Number: ${{ github.run_number }} Run ID: ${{ github.run_id }})
            BUILDID=${{ github.run_id }}
            BUILDNUMBER=${{ github.run_number }}
            SOURCE_COMMIT=${{ github.sha }}
          no-cache: true
          push: true