name: Test and Build

on:
  push:
    branches: 
      - master
      - dev
    paths-ignore:
      - 'README.md'
      - '.github/workflows/update-dockerhub.yml'
      - '.github/workflows/website_build.yml'
      - 'docs'
  pull_request:
    branches: 
      - master
      - dev
      - 'renovate/**'
      - 'feature/**'
    paths-ignore:
      - 'README.md'
      - '.github/workflows/update-dockerhub.yml'
      - '.github/workflows/website_build.yml'
      - 'docs'
  workflow_dispatch: # Allows action to be run manually from the Actions tab

jobs:
  build-docker:
      runs-on: 'ubuntu-latest'
      steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.0.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: get dependencies
        run: make composer-install-dev; make npm-install-gh
      - name: make foldersctructure and layout images
        run: make folder-structure-dev; make layout-images-dev         
      - name: Login to DockerHub
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Linux Image
        if: ${{ github.event_name == 'pull_request' }}
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v7
          tags: |
            lan2play/eventula-manager:latest
          build-args: |
            BUILDNODE=GitHub (Run Number: ${{ github.run_number }} Run ID: ${{ github.run_id }})
            BUILDID=${{ github.run_id }}
            BUILDNUMBER=${{ github.run_number }}
            SOURCE_COMMIT=${{ github.sha }}
            SOURCE_REF=${{ github.ref }}
          no-cache: true
          push: false      
      - name: Build and push Linux Image
        if: ${{ startsWith(github.ref, 'refs/heads/master') && github.event_name == 'push' }}
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v7
          tags: |
            lan2play/eventula-manager:latest
          build-args: |
            BUILDNODE=GitHub (Run Number: ${{ github.run_number }} Run ID: ${{ github.run_id }})
            BUILDID=${{ github.run_id }}
            BUILDNUMBER=${{ github.run_number }}
            SOURCE_COMMIT=${{ github.sha }}
            SOURCE_REF=${{ github.ref }}
          no-cache: true
          push: true
      - name: Build and push Linux Image dev
        if: ${{ startsWith(github.ref, 'refs/heads/dev') && github.event_name == 'push' }}
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v7
          tags: |
            lan2play/eventula-manager:dev
          build-args: |
            BUILDNODE=GitHub (Run Number: ${{ github.run_number }} Run ID: ${{ github.run_id }})
            BUILDID=${{ github.run_id }}
            BUILDNUMBER=${{ github.run_number }}
            SOURCE_COMMIT=${{ github.sha }}
            SOURCE_REF=${{ github.ref }}
          no-cache: true
          push: true